title: Journal
description: >-
  Here, we can track what we need to do for a whole year. It can help in
  managing our time and be minded of what should be done.
template:
  repo: journal-template
  name: journal
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
